config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :pools do
    member do
      get :bets
      get :results
      get :elimination_bets
    end
    resources :registrations, only: [:index, :destroy] do
      get :register, on: :member
    end
  end

  resources :bets, except: [:new, :create, :show]

  resources :users do
    member do
      get :bets
      post :create_bets
      delete :destroy_bets
    end
  end

  resources :matches, except: :show do
    resources :scores, except: :show
  end

  resources :elimination_matches, except: :show
  resources :elimination_bets, except: :show


  resources :groups, except: :show

  resources :answers, only: :update

  get 'documents/my_bets/:pool_id', to: "documents#my_bets", as: 'documents_my_bets'
  get 'documents/all_bets/:pool_id', to: "documents#all_bets", as: 'documents_all_bets'

  post '/contact', to: 'home#contact', as: 'contacts'
  post '/registrations', to: 'home#registration', as: 'registrations'
  get '/dashboard', to: 'dashboard#index', as: 'dashboard'
  root 'home#index'
end

app/models/pool.rb
class Pool < ActiveRecord::Base
  ### relations
  has_and_belongs_to_many :matches
  has_and_belongs_to_many :elimination_matches
  has_many :bets, dependent: :delete_all
  has_many :elimination_bets, dependent: :delete_all
  has_many :answers, dependent: :delete_all
  has_many :registrations
  has_many :users, -> { distinct }, through: :bets
  ### validations
  validates_presence_of :name, :end_date, :price, :pot_percentage
  ### scopes
  scope :active, -> { where(completed: false) }
  scope :inactive, -> { where(completed: true) }

  ## instance methods
  def pot_size
    (users.count * price) * (pot_percentage / 100)
  end

  def users_classification
    classification = {}
    users.each do |user|
      classification[user.nickname] = [user.total_points_in_pool(self), user.total_elimination_points_in_pool(self),
        user.bonus_points]
    end
    Hash[classification.sort_by{|k,v| v[0].to_i + v[1].to_i + v[2].to_i}.reverse]
  end

  ## class methods
    def bets_of_user(user)
      bets.includes(:match).where(user: user)
    end

    def elimination_bets_of_user(user)
      elimination_bets.includes(:elimination_match).
      where(user: user).
      order("elimination_matches.match_number")
    end

    def elimination_bets_of_user_by_round(user, round)
      elimination_bets_of_user(user).
      where("elimination_matches.round=?", round)
    end

    def self.active_for_user(user)
      array_pool = all.to_a
      user.pools.each do |user_pool|
        array_pool.delete(user_pool)
      end
      array_pool
    end
end

app/controllers/pools_controller.rb
class PoolsController < ApplicationController
  before_action :set_pool, except: [:index, :new, :create]
  before_action :check_status_of_clasification, only: :bets
  before_action :check_status_of_elimination, only: :elimination_bets
  authorize_resource

  def index
    @pools = Pool.all
  end

  def show
    if current_user.regular?
      @matches = @pool.matches.includes(:group).by_date(Date.current)
      @bets = current_user.bets_in_pool_with_date(@pool, Date.current)
      @elimination_matches = @pool.elimination_matches.by_date(Date.current)
      @elimination_bets = current_user.elimination_bets_in_pool_with_date(@pool, Date.current)
      @users = @pool.users
      @table = @pool.users_classification
    end
  end

  def results
    @bets = @pool.bets_of_user(current_user)
    @groups = Group.includes(:teams).all
  end

  def bets
    results
  end

  def elimination_bets
    @octavos_bets = @pool.elimination_bets_of_user_by_round(current_user, "Octavos")
    @cuartos_bets = @pool.elimination_bets_of_user_by_round(current_user, "Cuartos")
    @semi_bets = @pool.elimination_bets_of_user_by_round(current_user, "Semi-Final")
    @final = @pool.elimination_bets_of_user_by_round(current_user, "Final").first
    @otro = @pool.elimination_bets_of_user_by_round(current_user, "Otro").first
  end

  def new
    @pool = Pool.new
  end

  def edit
  end

  def create
    @pool = Pool.new(pool_params)
    if @pool.save
      redirect_to pools_path, notice: 'Pool was successfully created.'
    else
      render :new
    end
  end

  def update
    if @pool.update(pool_params)
      redirect_to pools_path, notice: 'Pool was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @pool.destroy
    redirect_to pools_url
  end

  private
    def set_pool
      @pool = Pool.find(params[:id])
    end

    def pool_params
      params[:pool].permit!
    end

    def check_status_of_clasification
      redirect_to(pool_path(@pool),
        notice: "El tiempo para completar tus pronosticos ha terminado") unless @pool.active_clasification
    end

    def check_status_of_elimination
      redirect_to(pool_path(@pool),
        notice: "El tiempo para completar tus pronosticos ha terminado") unless @pool.active_elimination
    end
end

app/helpers/pools_helper.rb
module PoolsHelper
  def highlight_current_user(value, method)
    "highlight" if current_user.send(method) == value
  end

  def dropdown_button(name)
    link_to "#", class: "btn btn-default dropdown-toggle", data: { toggle: "dropdown" } do
      raw("#{name} ") + content_tag(:span, nil, class: "caret")
    end
  end

  def div_for_elimination_match(match)
    content_tag(:div, class: "elimination_match center-block", id: match.id,
      data: { match_to_winner: match.match_to_winner, match_to_loser: match.match_to_loser,
      select: match.select, round: match.round }) do
        yield
      end
  end
end

app/views/pools/_elimination_bets_for_today.html.erb
<div>
  <table class="table-dashboard">
    <tr class="header">
      <td colspan="7">PREDICCIÓN PARA HOY - RONDA DE ELIMINACIÓN</td>
    </tr>
    <tr class="sub-header">
      <td>Nro</td>
      <td>Partido</th>
      <td>Ciudad</td>
      <td>Fecha</td>
      <td>Hora</th>
    </tr>
    <% elimination_bets.includes(:elimination_match).each do |bet| %>
      <% bet.elimination_match.get_teams %>
      <tr class="row-game <%= cycle("odd", "even") %>">
        <td><%= bet.elimination_match.match_number %></td>
        <td>
          <span><%= bet.find_local_team.try(:abbr) %></span>
            <%= flag(bet.find_local_team) %>
          <span><%= bet.score_to_s %></span>
            <%= flag(bet.find_visitor_team) %>
          <span><%= bet.find_visitor_team.try(:abbr) %></span>
        </td>
        <td><%= bet.elimination_match.stadium %></td>
        <td><%= bet.elimination_match.date.strftime("%d-%m") %></td>
        <td><%= bet.elimination_match.hour %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/pools/_elimination_matches_for_today.html.erb
<div>
  <table class="table-dashboard">
    <tr class="header">
      <td colspan="7">PARTIDOS PARA HOY - RONDA DE ELIMINACIÓN</td>
    </tr>
    <tr class="sub-header">
      <td>Nro</td>
      <td>Partido</th>
      <td>Ciudad</td>
      <td>Fecha</td>
      <td>Hora</th>
    </tr>
    <% elimination_matches.each do |match| %>
      <% match.get_teams  %>
      <tr class="row-game <%= cycle("odd", "even") %>">
        <td><%= match.match_number %></td>
        <td>
          <span><%= match.local_team.abbr %></span>
            <%= flag(match.local_team) %>
          <span><%= match.score_to_s %></span>
            <%= flag(match.visitor_team) %>
          <span><%= match.visitor_team.abbr %></span>
        </td>
        <td><%= match.stadium %></td>
        <td><%= match.date.strftime("%d-%m") %></td>
        <td><%= match.hour %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/pools/_form.html.erb
<%= simple_form_for(@pool) do |f| %>
  <%= f.error_notification %>
  <%= f.input :name %>
  <%= f.input :price %>
  <%= f.input :pot_percentage %>
  <%= f.input :end_date, as: :string, input_html: { class: "datepicker"} %>
  <%= f.input :completed %>
  <%= f.input :active_clasification, as: :boolean %>
  <%= f.input :active_elimination, as: :boolean %>
  <%= f.input :match_ids, collection: Match.all,
    input_html: { id: "multiselect-matches", multiple: true } %>
  <%= f.input :elimination_match_ids, collection: EliminationMatch.all,
    input_html: { id: "multiselect-e-matches", multiple: true } %>
  <%= f.button :submit, class: "btn btn-success" %>
  <%= link_to "Volver", pools_path, class: "btn btn-default" %>
<% end %>

app/views/pools/_matches_for_today.html.erb
<div>
  <table class="table-dashboard">
    <tr class="header">
      <td colspan="7">PARTIDOS PARA HOY</td>
    </tr>
    <tr class="sub-header">
      <td></td>
      <td>Nro</td>
      <td>Grupo</td>
      <td>Partido</th>
      <td>Ciudad</td>
      <td>Fecha</td>
      <td>Hora</th>
    </tr>
    <% matches.each do |match| %>
      <% match.get_teams  %>
      <tr class="row-game <%= cycle("odd", "even") %>">
        <%= td_color(match.group.color) %>
        <td><%= match.match_number %></td>
        <td><%= match.group.name %></td>
        <td>
          <span><%= match.local.abbr %></span>
            <%= flag(match.local) %>
          <span><%= match.score_to_s %></span>
            <%= flag(match.visitor) %>
          <span><%= match.visitor.abbr %></span>
        </td>
        <td><%= match.stadium %></td>
        <td><%= match.date.strftime("%d-%m") %></td>
        <td><%= match.hour %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/pools/_options_panel.html.erb
<%= form_panel(@pool.name.upcase) do %>
  <% if @pool.active_clasification %>
  <%= link_to "Realizar Apuestas", bets_pool_path(@pool), class: "btn btn-default" %>
  <% end %>
  <% if @pool.active_elimination %>
  <%= link_to "Eliminacion", elimination_bets_pool_path(@pool), class: "btn btn-default" %>
  <% end %>
  <%= link_to "Ver Resultados", results_pool_path(@pool), class: "btn btn-default" %>
  <div class="btn-group">
    <%= dropdown_button("Ver mis apuestas") %>
    <ul class="dropdown-menu" role="menu">
      <li>
        <%= link_to "archivo PDF", documents_my_bets_path(@pool, format: :pdf), target: "_blank" %>
      </li>
      <li>
        <%= link_to "vista HTML", documents_my_bets_path(@pool), target: "_blank" %>
      </li>
    </ul>
  </div>
  <div class="btn-group">
    <%= dropdown_button("Ver todas las apuestas") %>
    <ul class="dropdown-menu" role="menu">
      <li>
        <%= link_to "archivo PDF", documents_all_bets_path(@pool, format: :pdf), target: "_blank" %>
      </li>
      <li>
        <%= link_to "vista HTML", documents_all_bets_path(@pool), target: "_blank" %>
      </li>
    </ul>
  </div>

<% end %>

app/views/pools/_pool_bets.html.erb
<div class="group-table-widget">
<%= content_tag(:div, class: "group", id: "g#{group.id}", data: { id: group.id,
    teams: group.teams.map(&:name_js) }) do %>
  <% if bets.any? %>
      <div class="center">
        <b>Espera a que el fondo de las casillas de resultados esten de color verde
        para verificar que tu predicción ha sido guardada.</b>
      </div>
      <br>
      <table class="matches-widget">
        <tr class="header-widget">
          <td style="<%= set_background_color(group.color) %>">
            <%= group.name.split(" ")[1] %>
          </td>
          <% group.teams.each do |team| %>
            <td><ul><li><%= flag(team) %></li><li><%= team.abbr %></li></ul></td>
          <% end %>
          <td><%= image_tag("copa.png") %></td>
        </tr>
        <tr class="sub-header-widget">
          <td>FECHA</td>
          <td colspan="5">QUINIELA</td>
        </tr>
        <% bets.each do |bet| %>
          <% bet.match.get_teams %>
            <tr class="row-widget <%= cycle('odd', 'even')%>" id="bet-<%= bet.id %>">
              <!-- FECHA Y ESTADIO -->
              <td><ul>
                <li><%= bet.match.date.strftime("%d/%m") %></li>
                <li><%= bet.match.hour %></li>
                <li><%=raw bet.match.stadium.gsub("  ", "<br>") %></li>
              </ul></td>
              <!-- APUESTAS -->
              <td colspan="5">
                <ul>
                  <li class="li-bet">
                    <%= form_for bet, remote: true do |f| %>
                    <%= f.hidden_field :match_time, value: "full-time" %>
                    <div class="team"><%= bet.match.local.abbr %></div>
                    <div class="flag"><%= big_flag(bet.match.local) %></div>
                    <div class="field">
                      <%= f.text_field :local, class: "input-bet",
                        data: { team: bet.match.local.name_js } %>
                    </div>
                    <div class="field">
                      <%= f.text_field :visitor, class: "input-bet",
                        data: { team: bet.match.visitor.name_js } %>
                    </div>
                    <div class="flag"><%= big_flag(bet.match.visitor) %></div>
                    <div class="team"><%= bet.match.visitor.abbr %></div>
                    <% end %>
                  </li>
                </ul>
              </td>
            </tr>
        <% end %>
      </table>

      <table class="classification classification-widget" id="group_<%= group.id %>">
        <tr class="header-widget">
          <td style="<%= set_background_color(group.color) %>">
            <%= group.name.split(" ")[1] %>
          </td>
          <td>J</td>
          <td>G</td>
          <td>E</td>
          <td>P</td>
          <td>GF</td>
          <td>GC</td>
          <td>PTS</td>
        </tr>
        <% group.teams.each do |team| %>
          <tr class="row-team" id="<%= team.name_js %>" data-abrr="<%= team.abbr %>">
            <td><ul><li><%= flag(team) %></li><li><%= team.abbr %></li></ul></td>
            <td class="matches">0</td>
            <td class="win">0</td>
            <td class="draw">0</td>
            <td class="lose">0</td>
            <td class="goles_favor">0</td>
            <td class="goles_contra">0</td>
            <td class="points">0</td>
          </tr>
        <% end %>
        <tfoot>
          <tr class="row-team row-classified">
            <td colspan="8">
              <span class="teams-classified"></span>
            </td>
          </tr>
          <tr><td class="fake-space"></td></tr>
        </tfoot>
      </table>
  <% else %>
    No hay apuestas para este grupo
  <% end %>
<% end %>
</div>

app/views/pools/_pool_elimination_bets.html.erb
<%= div_for_elimination_match(eb.elimination_match) do %>
  <div class="info-elimination-bet">
    <% eb.elimination_match.to_s %>
    <%= "[#{eb.elimination_match.match_number}]  #{eb.elimination_match.round}"  %><br>
    <% if eb.elimination_match.round == "Octavos" %>
      <% local_name = eb.elimination_match.local_name %>
      <% visitor_name = eb.elimination_match.visitor_name %>
      <%= truncate(eb.elimination_match.to_s, length: 18) %><br>
    <% else %>
      <% local_name = eb.local_name %>
      <% visitor_name = eb.visitor_name %>
      <%= truncate(eb.to_s, length: 18) %><br>
    <% end %>
    <%= "#{eb.elimination_match.date.strftime('%d-%m-%Y')}  #{eb.elimination_match.hour}" %>
  </div>
  <%= form_for eb, remote: true do |f| %>
    <%= f.hidden_field :local_name, value: local_name, id: "local-name"  %>
    <%= f.hidden_field :visitor_name, value: visitor_name, id: "visitor-name" %>
    <ul class="flag-result pull-left">
      <% if eb.find_local_team %>
        <li class="local-flag" data-class="local">
          <%= flag(eb.find_local_team)%>
        </li>
      <% else %>
        <li class="local-flag" data-class="local">
          <%= flag(eb.elimination_match.local_team)%>
        </li>
      <% end %>
      <li><%= f.text_field :local, id: "local-score" %></li>
    </ul>
    <ul class="flag-result pull-right">
      <% if eb.find_visitor_team %>
        <li class="visitor-flag" data-class="visitor">
          <%= flag(eb.find_visitor_team)%>
        </li>
      <% else %>
        <li class="visitor-flag" data-class="visitor">
          <%= flag(eb.elimination_match.visitor_team)%>
        </li>
      <% end %>
      <li><%= f.text_field :visitor, id: "visitor-score" %></li>
    </ul>
    <div class="clearfix" style="margin-bottom: 5px"></div>
    <div class="submit-button">
      <%= link_to "Enviar", "#", class: "btn btn-default btn-xs link-prueba" %>
    </div>
  <% end %>
<% end %>
<% unless eb.elimination_match.round == "Final" || eb.elimination_match.round == "Otro" %>
  <div class="triangle-down center-block"></div>
<% end %>

app/views/pools/bets.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <div class="pool-header">
      <%= @pool.name %> - Apuestas
      <div class="pull-right">
        <%= back_table_button pool_path(@pool) %>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <div class="container-widgets">
      <div class="group-links-widget">
        <% @groups.each do |group| %>
          <%= link_to group.name, "#", class: "group-link btn btn-widget btn-sm",
            style: set_background_color(group.color) ,data: { id: group.id } %>
        <% end %>
      </div>
      <% @groups.each do |group| %>
        <%= render partial: "pool_bets", locals: { group: group, bets: @bets.of_group(group) } %>
      <% end %>
    </div>
  </div>
</div>
<% if current_user.answer_of_pool(@pool).present? %>
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <div class="container-widgets" style="text-align: left">
        <%= render partial: "answers_form", locals: { answer: current_user.answer_of_pool(@pool) } %>
      </div>
    </div>
  </div>
<% end %>

app/views/pools/edit.html.erb
<%= form_panel("Editar Quiniela") do %>
  <%= render 'form' %>
<% end %>

app/views/pools/elimination_bets.html.erb
<%= index_panel("Predicciones de Eliminacion", false, "#", pool_path(@pool) ) do %>
<table id="elimination-bets">
  <tr id="octavos">
    <% @octavos_bets.each do |eb| %>
      <td><%= render partial: "pool_elimination_bets", locals: { eb: eb } %></td>
    <% end %>
  </tr>
  <tr id="cuartos">
    <% @cuartos_bets.each do |eb| %>
      <td colspan="2"><%= render partial: "pool_elimination_bets", locals: { eb: eb } %></td>
    <% end %>
  </tr>
  <tr id="semi">
    <% @semi_bets.each do |eb| %>
      <td colspan="4"><%= render partial: "pool_elimination_bets", locals: { eb: eb } %></td>
    <% end %>
  </tr>
  <tr id="final">
    <td colspan="2"></td>
    <td colspan="2">
      <%= render partial: "pool_elimination_bets", locals: { eb: @final } %>
    </td>
    <td colspan="2">
      <%= render partial: "pool_elimination_bets", locals: { eb: @otro } %>
    </td>
    <td colspan="2"></td>
  </tr>

</table>
<% end %>

app/views/pools/index.html.erb
<%= index_panel("Quinielas", can?(:create, Pool), new_pool_path, dashboard_path ) do %>
  <% if @pools.any? %>
    <table class="table">
      <thead>
        <tr>
          <th>Nombre</th>
          <th>Partidos de Clas.</th>
          <th>Partidos de Elim.</th>
          <th>Limite</th>
          <th>Clasificacion</th>
          <th>Eliminacion</th>
          <th>Completada</th>
          <th class="center">Acciones</th>
        </tr>
      </thead>
      <tbody>
        <% @pools.each do |pool| %>
          <tr>
            <td><%= pool.name %></td>
            <td><%= pool.matches.count %></td>
            <td><%= pool.elimination_matches.count %></td>
            <td><%= pool.end_date %></td>
            <td><%= pool.active_clasification %></td>
            <td><%= pool.active_elimination %></td>
            <td><%= pool.completed %></td>
            <td class="center">
              <% if can? :read, pool %>
                <%= show_table_button pool %>
              <% end %>
              <% if can? :edit, pool %>
                <%= edit_table_button edit_pool_path(pool) %>
              <% end %>
              <% if can? :destroy, pool %>
                <%= destroy_table_button pool %>
              <% end %>
              <% if can? :read, Registration %>
                <%= registrations_table_button pool_registrations_path(pool)  %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <%=  mssg_for_empty_table %>
  <% end %>
<% end %>

app/views/pools/new.html.erb
<%= form_panel("Nueva Quiniela") do %>
  <%= render 'form' %>
<% end %>

app/views/pools/notice.html.erb
<h1>
  NO TIENES QUINIELAS ASIGNADAS
</h1>

app/views/pools/show.html.erb
<% if current_user.regular? %>
<div class="row">
  <div class="col-md-8">
    <%= render "options_panel" %>
    <% if @matches.any? %>
      <%= render partial: "matches_for_today", locals: { matches: @matches } %>
    <% end %>
    <% if @elimination_matches.any? %>
      <%= render partial: "elimination_matches_for_today",
        locals: { elimination_matches: @elimination_matches } %>
    <% end %>
    <% if @bets.any? %>
      <%= render partial: "bets_for_today", locals: { bets: @bets } %>
    <% end %>
    <% if @elimination_bets.any? %>
      <%= render partial: "elimination_bets_for_today",
        locals: { elimination_bets: @elimination_bets } %>
    <% end %>
    <div class="info-container">
      <div class="dashboard-info">
        <div class="description">PARTICIPANTES</div>
        <div class="info"><span><%= @users.count %></span></div>
      </div>
      <div class="dashboard-info">
        <div class="description">POTE EN BS.</div>
        <div class="info">
          <span><%= number_with_precision(@pool.pot_size, separator: ',', delimiter: '.') %></span>
        </div>
      </div>
      <div class="dashboard-info">
        <div class="description">MI POSICIÓN</div>
        <div class="info">
          <span><%= position_in_classification(@table, current_user.nickname) %></span>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <%= render partial: "clasification", locals: { classification: @table } %>
  </div>
</div>
<% end %>