config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :pools do
    member do
      get :bets
      get :results
      get :elimination_bets
    end
    resources :registrations, only: [:index, :destroy] do
      get :register, on: :member
    end
  end

  resources :bets, except: [:new, :create, :show]

  resources :users do
    member do
      get :bets
      post :create_bets
      delete :destroy_bets
    end
  end

  resources :matches, except: :show do
    resources :scores, except: :show
  end

  resources :elimination_matches, except: :show
  resources :elimination_bets, except: :show


  resources :groups, except: :show

  resources :answers, only: :update

  get 'documents/my_bets/:pool_id', to: "documents#my_bets", as: 'documents_my_bets'
  get 'documents/all_bets/:pool_id', to: "documents#all_bets", as: 'documents_all_bets'

  post '/contact', to: 'home#contact', as: 'contacts'
  post '/registrations', to: 'home#registration', as: 'registrations'
  get '/dashboard', to: 'dashboard#index', as: 'dashboard'
  root 'home#index'
end

app/models/match.rb
class Match < ActiveRecord::Base
  ### accesores
  attr_reader :visitor_team, :local_team
  ### relations
  has_many :scores
  has_many :bets
  belongs_to :group
  has_and_belongs_to_many :pools
  ### scopes
  default_scope -> { order([:match_number, :date]) }
  scope :by_date, ->(time) { where(date: time) }
  ### validations
  validates_presence_of :stadium, :date, :visitor_team_id, :local_team_id
  validate :check_teams

  ### instance methods
  def to_s
    get_teams
    "#{local_team.name} vs #{visitor_team.name}"
  end

  def get_teams
    @teams ||= Team.find([local_team_id, visitor_team_id])
    @teams.each do |team|
      @local_team = team if team.id == local_team_id
      @visitor_team = team if team.id == visitor_team_id
    end
  end

  def final_score
    scores.last
  end

  def score_to_s
    played? ? final_score.to_s : "por jugar"
  end

  def visitor
    @visitor_team || Team.find(visitor_team_id)
  end

  def local
    @local_team || Team.find(local_team_id)
  end

  def played?
    final_score.present?
  end

  private
    def check_teams
      if local_team_id == visitor_team_id
        errors[:visitor_team_id] = "No puedes elegir dos veces el mismo equipo"
      end
    end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: [:show, :edit, :update, :destroy]
  authorize_resource

  def index
    @matches = Match.includes(:group).all
  end

  def show
  end

  def new
    @match = Match.new
    @groups = Group.all.includes(:teams)
  end

  def edit
    @groups = Group.all.includes(:teams)
  end

  def create
    @match = Match.new(match_params)
    if @match.save
      redirect_to matches_path notice: 'Match was successfully created.'
    else
      @groups = Group.all.includes(:teams)
      render :new
    end
  end

  def update
    if @match.update(match_params)
      redirect_to matches_path, notice: 'Match was successfully updated.'
    else
      @groups = Group.all.includes(:teams)
      render :edit
    end
  end

  def destroy
    @match.destroy
    redirect_to matches_url
  end

  private
    def set_match
      @match = Match.find(params[:id])
    end

    def match_params
      params[:match].permit!
    end
end

app/helpers/matches_helper.rb
module MatchesHelper
  def check_match(match_score)
    match_score.present? ? match_score : "No jugado"
  end
  alias :cm :check_match
end

app/views/matches/_form.html.erb
<%= simple_form_for(@match) do |f| %>
  <%= f.error_notification %>
  <%= f.input :date, as: :string, input_html:{ class: 'datepicker'} %>
  <%= f.input :hour %>
  <%= f.input :stadium %>
  <%= f.input :match_number %>
  <%= f.input :group_id, collection: @groups, label_method: :name, value_method: :id,
    input_html: { class: 'chosen-select', data: { placeholder: "Seleccione Grupo"}  } %>
  <%= f.input :local_team_id, collection: @groups, as: :grouped_select, group_method: :teams,
    group_label_method: :name, label_method: :name, value_method: :id,
    input_html: { class: 'chosen-select', data: { placeholder: "Seleccione Equipo"}  } %>
  <%= f.input :visitor_team_id, collection: @groups, as: :grouped_select, group_method: :teams,
    group_label_method: :name, label_method: :name, value_method: :id,
    input_html: { class: 'chosen-select', data: { placeholder: "Seleccione Equipo"}  } %>
  <%= f.button :submit, class: "btn btn-success" %>
  <%= link_to "Volver", matches_path, class: "btn btn-default" %>
<% end %>

app/views/matches/edit.html.erb
<%= form_panel("Editar Partido") do %>
  <%= render 'form' %>
<% end %>

app/views/matches/index.html.erb
<div id="score-remote-form" style="display:none"></div>

<%= index_panel("Partidos de Clasificacion", can?(:create, Match), new_match_path,
  dashboard_path) do %>
  <% if @matches.any? %>
    <table class="table sorted" id="matches-table">
      <thead>
        <tr>
          <th></th>
          <th data-sort="int"><%= link_to "#", "#" %></th>
          <th data-sort="string"><%= link_to "Grupo", "#" %></th>
          <th data-sort="date"><%= link_to "Fecha", "#" %></th>
          <th>Hora</th>
          <th>Juego</th>
          <th>Estadio</th>
          <th>Resultado</th>
          <% if current_user.admin? %>
            <th colspan="3">Acciones</th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% @matches.each do |match| %>
          <tr>
            <%= td_color(match.group.color) %>
            <td><%= match.match_number %></td>
            <td><%= match.group.name %></td>
            <td><%= match.date.strftime('%d-%m-%Y') %></td>
            <td><%= match.hour %></td>
            <td><%= match.to_s %></td>
            <td><%= match.stadium %></td>
            <td id="match-score-<%= match.id %>"><%= match.score_to_s %></td>
            <% if current_user.admin? %>
              <td>
                <% if match.played? %>
                  <%= link_to_change_result edit_match_score_path(match, match.final_score), match.id %>
                <% else %>
                  <%= link_to_change_result new_match_score_path(match), match.id %>
                <% end %>
                <%= link_to_results match_scores_path(match) %>
                <%= edit_table_button edit_match_path(match) %>
                <%= destroy_table_button match %>
              </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <%=  mssg_for_empty_table %>
  <% end %>
<% end %>

app/views/matches/new.html.erb
<%= form_panel("Nuevo Partido") do %>
  <%= render 'form' %>
<% end %>